# Generated by Django 4.1 on 2022-08-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Username",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(verbose_name="Username from twitter")),
                (
                    "followers",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="followers"
                    ),
                ),
                (
                    "following",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="following"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Username",
                "verbose_name_plural": "Usernames",
            },
        ),
    ]
